/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.crmf.model.service;

/**
 *
 * @author standa
 */
public interface LoggingService {
    /**
     * Log that something happened.
     * 
     * @param code code of the event
     * @param message message generated by the system
     * @param action action being responsible for the event execution
     * @param objectType type of the object being worked with during the event
     * @param objectId object id of the related object type
     * @return new id of the Log entity
     */
    public Integer logEvent(Integer code, String message, String action, String objectType, Integer objectId);
}
